import type { NextPage } from "next";
import Head from "next/head";
import Header from "../components/Header";
import Projects from "../components/projects/Projects";

const Home: NextPage = () => {
	return (
		<div className="font-mono px-2">
			<Head>
				<title>Lmssieh | Portfolio</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="my-15">
				<Header />
			</div>
			<Projects />
		</div>
	);
};

export default Home;
